### ISSUE TITLE
save as mp3

### ISSUE THREAD

**Issue by felix0324324** [ghuyfel/flutter_azure_tts#12]
can i save the response as mp3?

**Comment by CognitiveJump** [comment]
Hey Felix,

I found example code for how to save as mp3 here:

https://nagomi-informal.net/archives/241

The website is in Japanese - but code on the page is in English (except for comments).  I just threw the website into an online translator and it gave me what I needed to know to save to mp3 and play back.  Much thanks to Nagomi!

**Comment by haroun-hajem** [comment]
Mark this as solved
