### ISSUE TITLE
Web app Play Uint8List audio on Safari iPhone device

### ISSUE THREAD

**Issue by aliakkawi** [ghuyfel/flutter_azure_tts#2]
Hi and thanks for creating the package, i am developing a Web Flutter application and i can successfully play Audio File using Chrome web browser on my Android device and Computer, but failed to play audio using Chrome on my iPhone or Safari browser on my Mac,
I am using the following code to convert Uint8List to  a Url

`
import 'dart:html' as html;

final blob = html.Blob([bytes], 'audio/mp3', 'native');
      final url = html.Url.createObjectUrlFromBlob(blob);`
Please advice what to do in order to play the url on iPhone Chrome browser too
Tnaks

**Comment by ghuyfel** [comment]
Hi,  thanks for using this package. I will have a look at it and revert back to you as soon as I can.

**Comment by ghuyfel** [comment]
> Hi and thanks for creating the package, i am developing a Web Flutter application and i can successfully play Audio File using Chrome web browser on my Android device and Computer, but failed to play audio using Chrome on my iPhone or Safari browser on my Mac, I am using the following code to convert Uint8List to a Url
> 
> ` import 'dart:html' as html;
> 
> final blob = html.Blob([bytes], 'audio/mp3', 'native'); final url = html.Url.createObjectUrlFromBlob(blob);` Please advice what to do in order to play the url on iPhone Chrome browser too Tnaks

I wasn't able to reproduce this issue. Did you come right? It sounds like it's a permission issue to me.
